# config/routes.yaml

# Home
app_index:
    path: /
    controller: App\Controller\IndexController::index
    methods: [GET]

# Authentication
app_registration:
    path: /users/register
    controller: App\Controller\UserController::registerPage
    methods: [GET,POST]

api_register:
    path: /api/register
    controller: App\Controller\RegistrationController::register
    methods: [POST]

app_login:
    path: /users/login
    controller: App\Controller\AuthController::login
    methods: [GET, POST]

app_logout:
    path: /users/logout
    controller: App\Controller\AuthController::logout
    methods: [GET,POST]

# Blog Posts
blog_list:
    path: /blogs/all
    controller: App\Controller\BlogController::list
    methods: [GET]

blog_new:
    path: /blogs/create
    controller: App\Controller\BlogController::new
    methods: [GET,POST]

blog_show:
    path: /blogs/{id}
    controller: App\Controller\BlogController::show
    methods: [GET]

blog_edit:
    path: /blogs/{id}/edit
    controller: App\Controller\HandleBlogController::edit
    methods: [GET, POST]

blog_delete:
    path: /blogs/{id}
    controller: App\Controller\HandleBlogController::delete
    methods: [POST]

# User-specific Blogs
my_blog_list:
    path: /users/blogs
    controller: App\Controller\BlogController::myBlogs
    methods: [GET]

add_comment:
    path: /blogs/{id}/comment
    controller: App\Controller\CommentsController::addComment
    methods: POST
