#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_hello:
    path: /hello
    controller: App\Controller\HelloController::index

app_registration:
    path: /register
    controller: App\Controller\RegistrationController::index
